### ISSUE TITLE
create a parameter to modify integer value for led

### ISSUE THREAD

**Issue by Cheesmaker** [Boomslangnz/OutputBlaster#3]
Hi and thank you for this work very usefull !
I use mamehooker to drive a Nextion (for jauges in m2 games and outrun2 fxt and maybe other i hope ....)  and leds  with a fake "arduino ledwizz" (from the pinmame world)  and outputs pwm value are between 0 to 48 in the ledwizz standard.
if i use Ultimarc I think it is 0 to 64 but it's never 100.
So i've got to recompile your work because mamehooker is not very user-friendly for calcul in real-time.

It could be cool and not just for me if a parameter in Outputblaster.ini define the max scale output. 

For the bit output no problem because there is a ledwizz command for that (set pin state).

**Comment by Boomslangnz** [comment]
Oh sure i can do that easy

I just set 100 as like 100 percent lol

**Comment by Boomslangnz** [comment]
https://mega.nz/file/hQ8EwKwY#3YruuUhMzTHUhrMrD8cfleskCHv4LlI2GNybN4aAVSQ

could you give this a test please. Added MaxScaleOutput to OutputBlaster.ini as requested and left default as 100 for now so just modify this to whatever number you want as 100 %

**Comment by Cheesmaker** [comment]
Thank you for this very quick release, I Try this evening and report.

**Comment by Cheesmaker** [comment]
hi, It's good thanks! 
I work on a little video for proof.  Thank you.  I try with Dirty D although i've got a big PC  sometimes mamehook crash without crashing lol (but i think it's a fake ledwizz pb because I send many much data to nextion without pb)
With win 10 a lot of people have problem to use the title bar hooking of mamehook , with your work and the start_mame  there is no pb so it could be interesting to declare all the Tekno game in your Dll to do homemade led script for SR3, Grid, etc. 

I will try a link with doflinx and report to you.

Thank you for this release

**Comment by Cheesmaker** [comment]
My test with the speaker led outputs of DD. It need 140ms to not crash  the ledwizz but this is just a test...It's very cool.

[https://mega.nz/file/aiJ3lYDD#b0_LQnBsGCPP7najotK4OwUcESqNQh7lbGrWBFBlzo0]

**Comment by Boomslangnz** [comment]
man that's really cool!

Honestly 140ms is gonna be fine, I think when I tested like M2 Emulator i ended up having it at like 300ms or noticed it would glitch the start button every now and then by flashing twice very quickly. Not sure these boards can handle being sent info too fast!

Would be awesome to show off your video if you have youtube link or such I can show it in the TeknoParrot discord channel. Most people don't even know what Output Blaster is! :D 

and your first person I even know of whos hooked up those lights that way with pwm

**Comment by Cheesmaker** [comment]
No matter you can post this video in the discord it's free of right! :). I will show soon my work with nextion in arcadecontrols. I'm on the jauges offset in model 3 now. I modify old arcade racecab to be over the original ! Thanks to SaylorS, Big P and NJZ all is now possible...(we renew (we is Retroplay44 or festivalretroplay) arcade machine and flipper for childrens hospital)
