### ISSUE TITLE
missing lamps for H2overdrive (with all infos in the issue)

### ISSUE THREAD

**Issue by Cheesmaker** [Boomslangnz/OutputBlaster#8]
Hi Boomslangz, 

After some search with cheat engine, I've found all the memory region needed to complete the outputs.  Cheat engine table = 
https://mega.nz/file/7zAVQAJI#N9hCDRqPXTHsCfDDsxl2p6FEDUJ-fJhjklNlKRNAQjs

The work is not all done because we( he you I'm not a programmer but I will take a look anyway)  need to do some stuff in your plug-in in order to flash or strobe led when the value is 2 or 3 for the boost lamp.

Also perhaps make the 4   7 segments digit in an unique (or one integer per 7 segments) integer speed value (I will work on the order of the segment with my own stuff with nextion HMI this week).

With that as usual I will do a modded cab with a real old hydro-thunder....it will not rest in the virtual world !

**Comment by Boomslangnz** [comment]
are you sure 1 is OFF and 0 is ON? seems weird

**Comment by Cheesmaker** [comment]
Not sure at all but it is that I deduct from the test mode lamps. This output are electrically not connect to the pwm output card with the rest of the lamp. This 4 digital outputs (3 under the throttle and the boost) are connected with the IO (and perhaps npn logic ). I see some video of tje arcade and it seems good.

**Comment by Boomslangnz** [comment]
https://mega.nz/file/5MsBkZpY#_GyyvNOrkoL-PFpNvunm5pnOZx2MBO_GlL7uz5zgdJk

try this out, i havent added the final speedometer led and boost meter but done the rest

ive done the speedo as seperate 4 digits aswell as having a interger speed value as requested

**Comment by Boomslangnz** [comment]
oh also, copy the OutputBlaster.ini across too, to adjust the pulse of Boost etc is inside for those new added outputs that flash

default is PulseRate=300 so you can play with that to find the flash rate you like

**Comment by Cheesmaker** [comment]
wow very cool. I'm at work this will be in test this evening (evening of France...)

**Comment by Boomslangnz** [comment]
[H2OverdriveTest2.zip](https://github.com/Boomslangnz/OutputBlaster/files/13224812/H2OverdriveTest2.zip)

here is updated version, ive added the speedometer led and brightness as independent outputs for each seperate LED and same for boostmeter so its alot of outputs!! 48 for each haha, but i think this is probably the best way to get it working correctly since sometimes certain LED are working while others are off etc and they have different brightness levels at same time so hopefully this will work

Please show me videos if you ever get this all working!!

**Comment by Boomslangnz** [comment]
[H2OverdriveTest3.zip](https://github.com/Boomslangnz/OutputBlaster/files/13225497/H2OverdriveTest3.zip)

ive added the words from attract i think (hopefully didnt miss any), but the outputs do not allow me to send strings eg words, i can only send numbers.

Ive sent them as virtual key codes https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

 unfortunately i also cannot send Uppercase or Lowercase so you will have to do that manually at your end

72 = H
70 = F
85 = U
78 = n
82 = r
65 = A
67 = C
69 = E
89 = y
80 = P
76 = L

eg for PLAy it would send

Digit1 = 80
Digit2 = 76
Digit3 = 65
Digit4 = 89

**Comment by Cheesmaker** [comment]
I'm in test now without outputing externally first and, my system (or I think mamehook and DDE communication) is little over. In game no real pb but in the attract mode it block sometimes (and it is weird but it is not the sleep time wich has a real impact, I think it is the quantity of data, haha..)

In order to test and because I don't have any contact with Howard I think we can test without :

154=Digit1Speed Brightness=100
155=Digit2Speed Brightness=100
156=Digit3Speed Brightness=100
157=Digit4Speed Brightness=100
158=Speedometer1 LED=0
159=Speedometer2 LED=0
160=Speedometer3 LED=0
161=Speedometer4 LED=0
162=Speedometer5 LED=0
163=Speedometer6 LED=0
164=Speedometer7 LED=0
165=Speedometer8 LED=0
166=Speedometer9 LED=0
167=Speedometer10 LED=0
168=Speedometer11 LED=0
169=Speedometer12 LED=0
170=Speedometer13 LED=0
171=Speedometer14 LED=0
172=Speedometer15 LED=0
173=Speedometer16 LED=0
174=Speedometer17 LED=0
175=Speedometer18 LED=0
176=Speedometer19 LED=0
177=Speedometer20 LED=0
178=Speedometer21 LED=0
179=Speedometer22 LED=0
180=Speedometer23 LED=0
181=Speedometer24 LED=0
182=Boostmeter1 LED=0
183=Boostmeter2 LED=0
184=Boostmeter3 LED=0
185=Boostmeter4 LED=0
186=Boostmeter5 LED=0
187=Boostmeter6 LED=0
188=Boostmeter7 LED=0
189=Boostmeter8 LED=0
190=Boostmeter9 LED=0
191=Boostmeter10 LED=0
192=Boostmeter11 LED=0
193=Boostmeter12 LED=0
194=Boostmeter13 LED=0
195=Boostmeter14 LED=0
196=Boostmeter15 LED=0
197=Boostmeter16 LED=0
198=Boostmeter17 LED=0
199=Boostmeter18 LED=0
200=Boostmeter19 LED=0
201=Boostmeter20 LED=0
202=Boostmeter21 LED=0
203=Boostmeter22 LED=0
204=Boostmeter23 LED=0
205=Boostmeter24 LED=0

I don't need the boost and speed led on/off, I can do with only the brightness in fact. 

If it is not good with that we can just try just to add the boost brightness stuff and not the speed brightness.

If you want you can just not compile every time I will do all test with your H2overdrive.cpp file because now I think it is not that you send (great great work) but the limit of DDE comunication we will have.

I'm not able to do that but a soft with netTCP output with the ability of Mamehooker to drive hardware should be a dream....



thank you

**Comment by Boomslangnz** [comment]
[OutputBlasterTest4.zip](https://github.com/Boomslangnz/OutputBlaster/files/13230223/OutputBlasterTest4.zip)

try this, i wanna get it working correctly before i push any code

**Comment by Boomslangnz** [comment]
Sorry to be clear, the pulse rate is not included on any of those speedometer or boostmeter outputs that have been added, instead that gets sent every 16ms

perhaps it’s too often for something to keep up so we could adjust that if necessary

**Comment by Cheesmaker** [comment]
I will do some test with a 2812 ring and nextion hmi and pacled63 tomorrow. It seems to be a succes with the ring boost (very cool), sometimes and only in the attract mode the debug view of mamehooker is fixed but it has no effect with the outputs of commands wich works.

**Comment by Boomslangnz** [comment]
[OutputBlasterTest5.zip](https://github.com/Boomslangnz/OutputBlaster/files/13255783/OutputBlasterTest5.zip)

ok ive added an option to OutputBlaster.ini for PulseRateSpeedo now so you can play with it to find a good timing on the speedo stuff

1 would every 16ms, 2 would be 32ms etc

**Comment by Cheesmaker** [comment]
It's perfect with 60ms in the main and with rate speedo. No freeze with the view of outputs and no delay with the game (this is the second matter with too many data )
Do some code in my hmi it seems there is a mistake with the "C" wich I don't receive. So after looking at the attract with it there is the world BOAT so I miss the T also (the B is good wich some luck)

https://mega.nz/file/6zJUyAZL#WmQBetcKbRKJSU45wZL0eYH5dHffIBxK4DyFbiDw0C8

Video with some upgrade with the ring.

We are close to finish :) .

**Comment by Boomslangnz** [comment]
Ok great

So just to confirm, we set pulse rate and pulse rate Speedo to 60ms or you have 60 added in OutputBlaster.ini? 

And we are currently missing C, B and T letters?

**Comment by Cheesmaker** [comment]
I have set sleep time to 60, also pulse rate speedo to 60. i've keep pulse rate to 300 for the flashing boost (it seems to be realist). 

yes C, B and T are missing.

**Comment by Boomslangnz** [comment]
[OutputBlasterTest6.zip](https://github.com/Boomslangnz/OutputBlaster/files/13262792/OutputBlasterTest6.zip)

ok ive added b, o and t (lowercase) and fixed up C now too

I have removed PulseRateSpeedo now so just set Sleep now since you had both set to 60 anyway and it will use that

b=66
o=79
t=84

**Comment by Boomslangnz** [comment]
you definately don't need DigitBrightness etc? i will delete all that from code if not necessary etc

**Comment by Cheesmaker** [comment]
Not at once but for someone else it could be more simple.
 No need to have digit and variable value in the same time for sure.
Perhaps you could just keep the command for digit as comment if someone want do some modification according to the hardware he use.

**Comment by Boomslangnz** [comment]
[OutputBlasterTest7.zip](https://github.com/Boomslangnz/OutputBlaster/files/13264814/OutputBlasterTest7.zip)

ok great thanks

here is final code hopefully with all that old code deleted etc, please ensure it all works fine now :)

**Comment by Cheesmaker** [comment]
It's great... FUN HEY PLAY H2O RACE BOAT 
 !...
Its good for me but you don't have link the speedo with the scale output value. it's always 100. Peharps a different parameter than the general in order to be not blind :)   thanks thanks thanks for all that work.

**Comment by Boomslangnz** [comment]
Sorry what do you mean about link the Speedo  with scale output? Do you mean the brightness?

**Comment by Boomslangnz** [comment]
I just had a test and seems the Speedo Brightness and Boost Brightness are working fine? They don't sit at 100 entire time at all

**Comment by Cheesmaker** [comment]
Yes the speedo brightness and boost brightbess are working fine with variation but the max value is fixed to 100. (in my case with ultimarc the max is 255 this is why I use the maxscalevalue with 255) I see all others values with a range 0 to 255 and the speedo and boost with a range 0 to 100.

**Comment by Boomslangnz** [comment]
Oh right I see, so you just want them to also scale max output same as the rest?

**Comment by Cheesmaker** [comment]
Yes. I think you've donne well. You can't respond to any request. If someone want something with different output scale (if you have different hardware in the same time like ledwizz(max 48) and ultimarc (max255)) it is always possible to compile yourself to do some complex stuff.

**Comment by Boomslangnz** [comment]
[OutputBlasterFINAL.zip](https://github.com/Boomslangnz/OutputBlaster/files/13294778/OutputBlasterFINAL.zip)

here should be final version, will scale to MaxScaleOutput now :)

**Comment by Cheesmaker** [comment]
It's perfect ! Now I have to work with the hardware, great thanks.
